# Generated by Django 4.1.2 on 2022-10-30 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("P", "Personal"), ("B", "Business")],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[("A", "Active"), ("I", "Inactive")],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "account_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("account_open_date", models.DateField(auto_now_add=True)),
                ("account_close_date", models.DateField(blank=True, null=True)),
                (
                    "account_transfer_limit",
                    models.DecimalField(
                        decimal_places=2, default=100000.0, max_digits=10
                    ),
                ),
                (
                    "account_withdrawal_limit",
                    models.DecimalField(
                        decimal_places=2, default=50000.0, max_digits=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_id",
                    models.BigIntegerField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_email", models.EmailField(max_length=254)),
                (
                    "customer_gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("customer_phone", models.CharField(max_length=15, unique=True)),
                ("customer_address", models.CharField(max_length=100)),
                ("customer_city", models.CharField(max_length=100)),
                ("customer_state", models.CharField(max_length=100)),
                ("customer_country", models.CharField(max_length=100)),
                ("customer_dob", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_name", models.CharField(max_length=100)),
                ("rule_description", models.CharField(max_length=100)),
                (
                    "rule_status",
                    models.CharField(
                        choices=[("A", "Active"), ("I", "Inactive")],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("rule_created", models.DateTimeField(auto_now_add=True)),
                ("rule_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("D", "Deposit"),
                            ("W", "Withdrawal"),
                            ("T", "Transfer"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("transaction_description", models.CharField(max_length=100)),
                (
                    "transaction_status",
                    models.CharField(
                        choices=[("S", "Success"), ("F", "Failed")], max_length=1
                    ),
                ),
                (
                    "transaction_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="m_core.account"
                    ),
                ),
                (
                    "transaction_receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_receiver",
                        to="m_core.account",
                    ),
                ),
                (
                    "transaction_sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_sender",
                        to="m_core.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[("C", "Credit"), ("D", "Debit")],
                        default="D",
                        max_length=1,
                    ),
                ),
                ("card_status", models.CharField(max_length=1)),
                ("card_created", models.DateTimeField(auto_now_add=True)),
                ("card_expiry", models.DateField()),
                ("card_number", models.CharField(max_length=16, unique=True)),
                (
                    "card_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="m_core.account"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="m_core.customer",
            ),
        ),
    ]
