# Generated by Django 4.1.2 on 2022-10-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m_core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="id",
        ),
        migrations.AlterField(
            model_name="account",
            name="account_number",
            field=models.BigIntegerField(
                editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("A", "Active"),
                    ("I", "Inactive"),
                    ("C", "Closed"),
                    ("B", "Blocked"),
                ],
                default="A",
                max_length=1,
            ),
        ),
    ]
