# Generated by Django 4.1.2 on 2022-10-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m_core", "0002_remove_account_id_alter_account_account_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_name", models.CharField(max_length=100)),
                ("offer_description", models.CharField(max_length=100)),
                (
                    "offer_status",
                    models.CharField(
                        choices=[("A", "Active"), ("I", "Inactive")],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("L", "Loan"),
                            ("I", "Insurance"),
                            ("C", "Credit Card"),
                        ],
                        default="L",
                        max_length=1,
                    ),
                ),
                ("offer_created", models.DateTimeField(auto_now_add=True)),
                ("offer_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Rule",
        ),
    ]
