# Generated by Django 4.1.2 on 2022-10-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("m_core", "0003_offers_delete_rule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionrecord",
            name="transaction_account",
        ),
    ]
