# Generated by Django 4.1.2 on 2022-10-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m_core", "0004_remove_transactionrecord_transaction_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_number",
            field=models.BigIntegerField(
                primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.BigIntegerField(
                primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
