# Generated by Django 4.1.2 on 2022-10-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m_core", "0006_rename_offers_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_number",
            field=models.BigIntegerField(
                default=0, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="offer_description",
            field=models.CharField(max_length=250),
        ),
    ]
