# Generated by Django 4.1.2 on 2022-10-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m_core", "0007_alter_account_account_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.BigIntegerField(
                default=0, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
